### ISSUE TITLE
Setting up visual constants shared to all trowel components

### ISSUE THREAD

**Issue by LoicGoyet** [Trowel/Trowel#24]
In order to provide by default, a coherent and consistent UI through all the friends of trowel components or even the non-official components. We need to set up inside trowel-core library some constants that will be common and not overwritten like
* font-sizes
* colors
* font-family
* spacings

Provide them as answer to this issue.

Once those constants setted up by the @Trowel/design-team  , we will materialize them into code that will be easily used and overwritten through configuration.

**Comment by LoicGoyet** [comment]
detailed list of required constants

* colors (5 lvl of grey + semantics colors)
* font-family (main + fallbacks)
* font-sizes (3/4 lvl of sizes)
* padding x y for components (no needs of sizes declinaisons because based on em's)
* grid gutter space for containers and grids
* line-height
* border-radius

**Comment by milsr2d2** [comment]
Here's the constants !

```scss
$colors: (
   'gray-light': rgb(248, 248, 250),
   'gray-medium': rgb(232, 232, 236),
   'gray-dark': rgb(207, 207, 213),
   'gray-darker': rgb(155, 155, 157),
   'primary': rgb(31, 13, 51),
   'success': rgb(55, 211, 189),
   'warning': rgb(255, 176, 0),
   'danger': rgb(253, 65, 100),
);

$font-sizes: (
   'xs': 0.65rem,
   'sm': 0.8rem,
   'md': 1rem,
   'lg': 1.2rem,
);

$font-family: 'Open Sans', verdana, sans-serif;
$line-height-component: 1.2;
$padding-vertical: 0.65em;
$padding-horizontal: 1.65em;
$grid-gutter-width: 2rem;
$border-width: 0.0625em;
$border-radius: 0.2em;
```
